create table if not exists profiles (
  id uuid primary key,
  name text not null,
  role text not null default 'user',
  created_at timestamp with time zone default now()
);

create table if not exists favorites (
  id bigint generated by default as identity primary key,
  user_id uuid,
  title text not null,
  notes text not null,
  created_at timestamp with time zone default now()
);

alter table profiles enable row level security;
alter table favorites enable row level security;

create policy "profiles_public_read"
on profiles
for select
using (true);

create policy "favorites_public_read"
on favorites
for select
using (true);

create policy "favorites_public_insert"
on favorites
for insert
with check (true);
